#!/usr/bin/env bash
#-*- mode: sh -*-

export PROJECT_ROOT=$(pwd)
export PATH=$PROJECT_ROOT/env:$PATH

function build() {
    local cflags="-std=c11 -pedantic-errors -fextended-identifiers -g -x c \
                  -Wno-format-contains-nul -Wno-format-security"

    local lflags="-lm"

    gcc $cflags -o "$PROJECT_ROOT/raytrace" main.c $lflags
}
