#!/usr/bin/env bash
#-*- mode: sh -*-

export PROJECT_ROOT=$(pwd)
export PATH=$PROJECT_ROOT/env:$PATH

source gs.sh

function build() {
    if [[ $(has_help_flag $args) ]]; then
        echo "Usage: build [options]"
        return
    fi

    if [[ ! -f env/build ]]; then
        mkdir -p env/build
    fi

    local cflags="-std=c11 -pedantic-errors -fextended-identifiers -g -x c \
                  -Wno-format-contains-nul -Wno-format-security"

    local lflags="-lm"

    gcc $cflags -o "$PROJECT_ROOT/env/build/main" main.c $lflags
}

function run() {
    if [[ ! -f env/build/main ]]; then
        echo "Call \`build' first"
        return
    fi

    $PROJECT_ROOT/env/build/main
}
